#
# Copyright (C) 2007, Guennadi Liakhovetski <lg@denx.de>
#
# (C) Copyright 2011 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y := mx6var_som.o mx6var_eeprom_v1.o mx6var_eeprom_v2.o mx6var_legacy.o
