void setup_pcie_padsq(void);
void setup_enet_pads_resetq(void);
void setup_enet_padsq(void);
void setup_enet_pads_finalq(void);
void setup_uart1_padsq(void);
void setup_usdhc3_padsq (void);
void setup_usdhc2_padsq (void);
void setup_usdhc1_padsq (void);
void setup_di0_padsq(void);

void setup_pcie_padsdl(void);
void setup_enet_pads_resetdl(void);
void setup_enet_padsdl(void);
void setup_enet_pads_finaldl(void);
void setup_uart1_padsdl(void);
void setup_usdhc3_padsdl (void);
void setup_usdhc2_padsdl (void);
void setup_usdhc1_padsdl(void);
void setup_di0_padsdl(void);
void setup_i2c_padq(void);
void setup_i2c_paddl(void);
