# (C) Copyright 2015 Freescale Semiconductor, Inc.
# (C) Copyright 2016 Variscite Ltd.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y  := mx7dvar_som.o mx7dvar_eeprom.o
obj-$(CONFIG_SPL_BUILD) += spl.o
