#
# Copyright 2017 NXP
# Copyright 2019-2020 Variscite Ltd.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += imx8qm_var_som.o
obj-y += ../common/mmc.o ../common/imx8_eeprom.o
obj-$(CONFIG_DM_VIDEO) += ../common/video.o
obj-$(CONFIG_FEC_MXC) += ../common/eth.o
obj-$(CONFIG_IMX8_BOARD_INIT_DRAM) += ../common/imx8_dram.o
obj-$(CONFIG_SPL_BUILD) += spl.o

